server {
    listen 80;

    # Identity Service (FastAPI)
    location /auth/ {
        proxy_pass http://identity_service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # Routes incoming static asset requests to the shared volume
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
   # Order & Catalog Service (Django)
    location /api/ {
        # REMOVE the path after the port.
        # Just the hostname and port ensures the full URI is passed.
        proxy_pass http://order-service:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Admin (Special case)
    location /admin/ {
        proxy_pass http://order-service:8000/admin/;
        proxy_set_header Host $host;
    }
}
