# Generated by Django 5.2.16 on 2026-07-30 10:21

from django.db import migrations


def copy_stock_forward(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Inventory = apps.get_model("inventory", "Inventory")
    StockTransaction = apps.get_model("inventory", "StockTransaction")

    for product in Product.objects.all():
        inventory = Inventory.objects.create(
            product=product, available_stock=product.stock, reserved_stock=0
        )
        # Create an initial restock transaction for audit log
        StockTransaction.objects.create(
            inventory=inventory,
            transaction_type="restock",
            quantity=product.stock,
            notes="Initial stock copied from Product model",
        )


def copy_stock_backward(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Inventory = apps.get_model("inventory", "Inventory")

    for inventory in Inventory.objects.all():
        product = inventory.product
        # Add available and reserved stock together
        product.stock = inventory.available_stock + inventory.reserved_stock
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        (
            "products",
            "0003_category_product_stock_product_category",
        ),  # Dependency on products app
    ]

    operations = [
        migrations.RunPython(copy_stock_forward, copy_stock_backward),
    ]
