global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "django-order-service"
    static_configs:
      - targets: ["order-service:8000"]
    metrics_path: /metrics/django

  - job_name: "identity-service"
    static_configs:
      - targets: ["identity_service:8001"]
    metrics_path: /metrics/identity
