# Generated by Django 5.2.16 on 2026-07-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_product_stock_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
