apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
  namespace: ecom
data:
  POSTGRES_DB: ecom_db
  POSTGRES_USER: ecom_user
  RABBITMQ_DEFAULT_USER: ecom_user
  RABBITMQ_DEFAULT_PASS: ecom_password
