apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ecom-config
            - secretRef:
                name: ecom-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecom
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
